
name: compile and host pdf of resume

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: install texlive
        run: sudo apt install texlive

      - name: install additional dependencies
        run: |
          tlmgr init-usertree
          tlmgr install pdfpages

      - name: complie resume
        run: pdflatex matthew_oley_resume.tex

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: './matthew_oley_resume.pdf'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
